# Generated by Django 4.1.5 on 2023-06-24 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('speaker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=255)),
                ('theme', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.category')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.DateTimeField()),
                ('session_duration', models.DurationField()),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='conference.conference')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speaker.speaker')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.PositiveIntegerField()),
                ('session_popularity', models.PositiveIntegerField()),
                ('speaker_ratings', models.PositiveIntegerField()),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='conference.conference')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.DateTimeField()),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='conference.attendee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.schedule')),
            ],
        ),
        migrations.AddField(
            model_name='attendee',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='conference.conference'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='sessions',
            field=models.ManyToManyField(to='conference.schedule'),
        ),
    ]
